name: Build

on:
  push:
    branch: main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: cofob
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .
